/**
 * Prisma Schema Generator
 *
 * Reads the parsed schema config and writes prisma/schema.prisma.
 * This file is auto-generated — do not edit manually.
 */

import fs from "fs";
import path from "path";
import { SchemaConfig, EntityConfig } from "./schema-loader";
import { getFieldType } from "./field-types";
import { toSnakeCase, toPascalCase, reverseRelationKey, foreignKeyName } from "./naming";

export function generatePrismaSchema(schema: SchemaConfig): string {
  const lines: string[] = [];

  // Header
  lines.push("// Auto-generated by schema engine. Do not edit manually.");
  lines.push("// Edit schema.yaml instead and restart the app.");
  lines.push("");
  lines.push("generator client {");
  lines.push('  provider = "prisma-client-js"');
  lines.push("}");
  lines.push("");
  lines.push("datasource db {");
  lines.push('  provider = "postgresql"');
  lines.push("}");
  lines.push("");

  // Generate models
  for (const [entityName, entity] of Object.entries(schema.entities)) {
    lines.push(...generateModel(entityName, entity, schema));
    lines.push("");
  }

  return lines.join("\n");
}

function generateModel(
  entityName: string,
  entity: EntityConfig,
  schema: SchemaConfig
): string[] {
  const modelName = toPascalCase(entityName);
  const lines: string[] = [];

  lines.push(`model ${modelName} {`);

  // Primary key
  lines.push("  id        Int      @id @default(autoincrement())");
  lines.push("  createdAt DateTime @default(now())");
  lines.push("  updatedAt DateTime @updatedAt");

  // Fields
  for (const [fieldName, field] of Object.entries(entity.fields)) {
    const ft = getFieldType(field.type);
    const prismaType = ft.prismaType;
    const optional = field.required ? "" : "?";
    const colName = toSnakeCase(fieldName);
    lines.push(`  ${colName} ${prismaType}${optional}`);
  }

  // Relations (belongs_to)
  if (entity.relations) {
    for (const [relName, rel] of Object.entries(entity.relations)) {
      const relModelName = toPascalCase(rel.entity);
      const fkName = foreignKeyName(toSnakeCase(relName));
      lines.push(`  ${fkName} Int?`);
      lines.push(
        `  ${relName} ${relModelName}? @relation(fields: [${fkName}], references: [id])`
      );
    }
  }

  // Reverse relations: find entities that belong_to this one
  for (const [otherName, otherEntity] of Object.entries(schema.entities)) {
    if (otherName === entityName) continue;
    if (!otherEntity.relations) continue;
    for (const [, rel] of Object.entries(otherEntity.relations)) {
      if (rel.entity === entityName) {
        const reverseFieldName = reverseRelationKey(otherName);
        const otherModelName = toPascalCase(otherName);
        lines.push(`  ${reverseFieldName} ${otherModelName}[]`);
      }
    }
  }

  lines.push("}");
  return lines;
}


export function writePrismaSchema(schema: SchemaConfig): void {
  const content = generatePrismaSchema(schema);
  const prismaDir = path.resolve(process.cwd(), "prisma");
  if (!fs.existsSync(prismaDir)) {
    fs.mkdirSync(prismaDir, { recursive: true });
  }
  fs.writeFileSync(path.join(prismaDir, "schema.prisma"), content, "utf-8");
}
