/**
 * Prisma Schema Generator
 *
 * Reads the parsed schema config and writes prisma/schema.prisma.
 * This file is auto-generated — do not edit manually.
 */

import fs from "fs";
import path from "path";
import { SchemaConfig, EntityConfig } from "./schema-loader";
import { getFieldType } from "./field-types";
import { toSnakeCase, toPascalCase, reverseRelationKey, foreignKeyName } from "./naming";

export function generatePrismaSchema(schema: SchemaConfig): string {
  const lines: string[] = [];

  // Header
  lines.push("// Auto-generated by schema engine. Do not edit manually.");
  lines.push("// Edit schema.yaml instead and restart the app.");
  lines.push("");
  lines.push("generator client {");
  lines.push('  provider = "prisma-client-js"');
  lines.push("}");
  lines.push("");
  lines.push("datasource db {");
  lines.push('  provider = "postgresql"');
  lines.push("}");
  lines.push("");

  // Generate models
  for (const [entityName, entity] of Object.entries(schema.entities)) {
    lines.push(...generateModel(entityName, entity, schema));
    lines.push("");
  }

  return lines.join("\n");
}

function generateModel(
  entityName: string,
  entity: EntityConfig,
  schema: SchemaConfig
): string[] {
  const modelName = toPascalCase(entityName);
  const lines: string[] = [];

  lines.push(`model ${modelName} {`);

  // Primary key
  lines.push("  id        Int      @id @default(autoincrement())");
  lines.push("  createdAt DateTime @default(now())");
  lines.push("  updatedAt DateTime @updatedAt");

  // Fields
  for (const [fieldName, field] of Object.entries(entity.fields)) {
    const ft = getFieldType(field.type);
    const prismaType = ft.prismaType;
    const optional = field.required ? "" : "?";
    const colName = toSnakeCase(fieldName);
    const decorators: string[] = [];
    if (field.unique) decorators.push("@unique");
    if (field.default !== undefined) {
      const val = typeof field.default === "boolean" || typeof field.default === "number"
        ? String(field.default)
        : `"${field.default}"`;
      decorators.push(`@default(${val})`);
    }
    const decStr = decorators.length ? " " + decorators.join(" ") : "";
    lines.push(`  ${colName} ${prismaType}${optional}${decStr}`);
  }

  // Relations (belongs_to)
  if (entity.relations) {
    for (const [relName, rel] of Object.entries(entity.relations)) {
      const relModelName = toPascalCase(rel.entity);
      const fkName = foreignKeyName(toSnakeCase(relName));
      const optional = rel.required ? "" : "?";
      const onDeleteMap = { cascade: "Cascade", restrict: "Restrict", set_null: "SetNull" } as const;
      const onDelete = rel.on_delete ? `, onDelete: ${onDeleteMap[rel.on_delete]}` : "";
      lines.push(`  ${fkName} Int${optional}`);
      lines.push(
        `  ${relName} ${relModelName}${optional} @relation(fields: [${fkName}], references: [id]${onDelete})`
      );
    }
  }

  // Reverse relations: find entities that belong_to this one
  for (const [otherName, otherEntity] of Object.entries(schema.entities)) {
    if (otherName === entityName) continue;
    if (!otherEntity.relations) continue;
    for (const [, rel] of Object.entries(otherEntity.relations)) {
      if (rel.entity === entityName) {
        const reverseFieldName = reverseRelationKey(otherName);
        const otherModelName = toPascalCase(otherName);
        lines.push(`  ${reverseFieldName} ${otherModelName}[]`);
      }
    }
  }

  // Single-column indexes (from field.indexed)
  for (const [fieldName, field] of Object.entries(entity.fields)) {
    if (field.indexed) {
      lines.push(`  @@index([${toSnakeCase(fieldName)}])`);
    }
  }

  // Auto-index FK columns from relations (skip if already the leftmost column
  // of a compound index — the compound index satisfies leftmost-prefix queries)
  if (entity.relations) {
    const compoundLeadCols = new Set(
      (entity.indexes ?? []).map(cols => {
        const c = cols[0];
        const isRelFk = c.endsWith("Id") && !!entity.relations?.[c.replace(/Id$/, "")];
        return isRelFk ? c : toSnakeCase(c);
      })
    );
    for (const [relName] of Object.entries(entity.relations)) {
      const fkName = foreignKeyName(toSnakeCase(relName));
      if (!compoundLeadCols.has(fkName)) {
        lines.push(`  @@index([${fkName}])`);
      }
    }
  }

  // Compound indexes (from entity.indexes)
  if (entity.indexes) {
    for (const cols of entity.indexes) {
      const colNames = cols.map(c => {
        // FK column names (e.g. "nurseId") are already in Prisma form — don't snake_case them
        const isRelFk = c.endsWith("Id") && !!entity.relations?.[c.replace(/Id$/, "")];
        return isRelFk ? c : toSnakeCase(c);
      });
      lines.push(`  @@index([${colNames.join(", ")}])`);
    }
  }

  lines.push("}");
  return lines;
}


export function writePrismaSchema(schema: SchemaConfig): void {
  const content = generatePrismaSchema(schema);
  const prismaDir = path.resolve(process.cwd(), "prisma");
  if (!fs.existsSync(prismaDir)) {
    fs.mkdirSync(prismaDir, { recursive: true });
  }
  fs.writeFileSync(path.join(prismaDir, "schema.prisma"), content, "utf-8");
}
