/**
 * Audit Alert Scanner
 *
 * Cron job that queries the AuditLog table for suspicious patterns
 * and emails the practice owner when thresholds are breached.
 *
 * Designed to run every 10 minutes:
 *   crontab: every 10 min — cd /path/to/customer-relations && npx tsx scripts/audit-alerts.ts
 *
 * Configuration (environment variables):
 *   ALERT_EMAIL       — recipient address (required, or script exits silently)
 *   RESEND_API_KEY    — Resend API key (required for real emails)
 *   EMAIL_FROM        — sender address (default: noreply@example.com)
 *   ALERT_WINDOW_MINS — how far back to scan (default: 10, should match cron interval)
 *   DATABASE_URL      — PostgreSQL connection string (required)
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const ALERT_EMAIL = process.env.ALERT_EMAIL;
const WINDOW_MINS = parseInt(process.env.ALERT_WINDOW_MINS || "10", 10);

interface Alert {
  severity: "high" | "medium";
  title: string;
  details: string;
}

async function scan(): Promise<Alert[]> {
  const since = new Date(Date.now() - WINDOW_MINS * 60_000);
  const alerts: Alert[] = [];

  const recentEvents = await prisma.auditLog.findMany({
    where: { timestamp: { gte: since } },
    orderBy: { timestamp: "desc" },
  });

  // ── Rule 1: Brute-force login attempts ──────────────────
  // 5+ failed logins for the same account in the window
  const loginFailures = recentEvents.filter((e) => e.action === "login_failed");
  const failuresByTarget = new Map<string, typeof loginFailures>();
  for (const event of loginFailures) {
    const key = event.entity_id;
    if (!failuresByTarget.has(key)) failuresByTarget.set(key, []);
    failuresByTarget.get(key)!.push(event);
  }
  for (const [target, events] of failuresByTarget) {
    if (events.length >= 5) {
      const ips = [...new Set(events.map((e) => e.ip).filter(Boolean))];
      alerts.push({
        severity: "high",
        title: `Brute-force login attempt: ${target}`,
        details: `${events.length} failed logins for "${target}" in the last ${WINDOW_MINS} minutes. Source IPs: ${ips.join(", ") || "unknown"}.`,
      });
    }
  }

  // ── Rule 2: Role escalation attempts ────────────────────
  // Any access_denied event
  const accessDenied = recentEvents.filter((e) => e.action === "access_denied");
  for (const event of accessDenied) {
    alerts.push({
      severity: "high",
      title: "Unauthorised access attempt",
      details: `${event.details ?? "No details"} — IP: ${event.ip ?? "unknown"}, at ${event.timestamp.toISOString()}.`,
    });
  }

  // ── Rule 3: CardDAV brute-force ─────────────────────────
  // 3+ failed CardDAV auth attempts in the window
  const carddavFailures = recentEvents.filter((e) => e.action === "carddav_auth_failed");
  if (carddavFailures.length >= 3) {
    const ips = [...new Set(carddavFailures.map((e) => e.ip).filter(Boolean))];
    alerts.push({
      severity: "high",
      title: "CardDAV brute-force attempt",
      details: `${carddavFailures.length} failed CardDAV auth attempts in the last ${WINDOW_MINS} minutes. Source IPs: ${ips.join(", ") || "unknown"}.`,
    });
  }

  // ── Rule 4: Data leaving the system ─────────────────────
  // Any export or AI external disclosure
  const dataExfil = recentEvents.filter(
    (e) => e.action === "export" || e.action === "ai_external_disclosure",
  );
  for (const event of dataExfil) {
    alerts.push({
      severity: "medium",
      title: event.action === "export" ? "Data export" : "Data sent to external AI",
      details: `User #${event.userId ?? "unknown"} — ${event.details ?? `${event.action} on ${event.entity}`} — IP: ${event.ip ?? "unknown"}, at ${event.timestamp.toISOString()}.`,
    });
  }

  return alerts;
}

async function sendAlertEmail(alerts: Alert[]): Promise<void> {
  if (!ALERT_EMAIL) return;

  const highCount = alerts.filter((a) => a.severity === "high").length;
  const subject = highCount > 0
    ? `[ALERT] ${highCount} security alert${highCount > 1 ? "s" : ""} — Customer Relations`
    : `[NOTICE] ${alerts.length} audit event${alerts.length > 1 ? "s" : ""} — Customer Relations`;

  const body = alerts
    .map(
      (a) =>
        `<div style="margin-bottom:16px;padding:12px;border-left:4px solid ${a.severity === "high" ? "#dc2626" : "#f59e0b"};background:#fafafa">` +
        `<strong>${a.severity === "high" ? "HIGH" : "MEDIUM"}: ${a.title}</strong>` +
        `<p style="margin:4px 0 0;color:#374151">${a.details}</p></div>`,
    )
    .join("\n");

  const html = `
    <h2>Audit Alert Report</h2>
    <p>The following suspicious activity was detected in the last ${WINDOW_MINS} minutes:</p>
    ${body}
    <hr>
    <p style="color:#6b7280;font-size:12px">This alert was generated by the audit scanner cron job. Review the full audit log in the database for additional context.</p>
  `;

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    // Stub mode
    console.log(`\n--- ALERT EMAIL (stub mode — set RESEND_API_KEY to send) ---`);
    console.log(`To: ${ALERT_EMAIL}`);
    console.log(`Subject: ${subject}`);
    for (const a of alerts) {
      console.log(`  [${a.severity.toUpperCase()}] ${a.title}: ${a.details}`);
    }
    console.log(`---\n`);
    return;
  }

  const { Resend } = await import("resend");
  const resend = new Resend(apiKey);

  await resend.emails.send({
    from: process.env.EMAIL_FROM || "Customer Relations <noreply@example.com>",
    to: ALERT_EMAIL,
    subject,
    html,
  });

  console.log(`Alert email sent to ${ALERT_EMAIL} (${alerts.length} alerts)`);
}

async function main() {
  if (!ALERT_EMAIL) {
    console.warn("ALERT_EMAIL not set — audit alerting disabled");
    process.exit(0);
  }

  try {
    const alerts = await scan();
    if (alerts.length === 0) {
      process.exit(0);
    }
    await sendAlertEmail(alerts);
  } catch (err) {
    console.error("Audit alert scanner failed:", err);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();
